### ISSUE TITLE
sns auth 처리 이슈

### ISSUE THREAD

**Issue by key-hh** [wear-at-org/wear-at#14]
- 이슈
  - react port 계속 바뀌는데 redirect 어떻게 대응할지
  - redux 사용자 정보  언제 채워야 할지
    - 중간 router(loading) -> 미완성 시 sns-login으로이동?
  - 사용자 정보가 채워지지 않은 상태로 동선 이동 시 어떻게 처리할지
    - 쿠키는 먼저 구워진 상태면 로그인 된걸로 보고 redux 업데이트 후 react 라우터 이동시 sns-login으로 유도할지

**Comment by kujarung** [comment]
1. 리액트 기본 포트 3000번을 유지 하는 게 좋을 거 같은 데, 계속 변경 된다면 실행 시 포트를 강제 하는 게 좋을 거 같습니다. 일단은 3000번으로 강제해서 푸시 하겠슴니다. 혹 다른 포트 원하시면 수정 하겠습니다.
2. 사실 지금은 유저정보에 대해서 딱히 redux에 저장 하고 있는 게 없습니다. 개인적으로는 로그인이 끝나고 나서 main으로 리다이렉트 할 때, 넣는 게 어떨지요.
3. 그냥 제 생각은
그냥 이메일 로그인 => 로그인페이지 -> 프로세스 -> 메인
sns로그인 => 로그인 페이지 => sns-login로 리다이렉트 -> 유저정보 확인 후 채웠다면 메인, 채운 게 남았다면 sns-login페이지에 남아 있기 정도가 어떨 지요.

**Comment by key-hh** [comment]
@kujarung 
1. 그럼 리액트 포트는 3000으로 개발하는걸로 규약을 정하도록 하겠습니다. 혹 바뀌는경우(재시작에 의한 포트변경 3001, 3002)는 redirect가 동작하지 않습니다.
2. 지금은 로그인여부 판별을 redux를 통해 하고있더라구요. 그래서 사용자정보를 redux에 추가하였습니다.
3. 현재 문제가 되는 시나리오는 "유저정보를 채우지 않은상태"에서 종료, 다시 접근하여 다른route로 이동시에 대한 처리입니다. 이미 로그인시 쿠키는 구워진상태라, 인증필요 라우트에 대해서 채워지지 않을 경우를 체크하여  "sns-login"로 유도하는 부분에 대한 처리가 필요해보이는데, 좋은방법 있을가요? 인증 프로세스를 바꾼다거나, 라우터 watcher? 같은곳에서 처리할 수도 있을것 같네요.
